# This is a basic workflow to help you get started with Actions

name: progress

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: output README
        run: |
          python3 progress.py > README.md
        
      - name: Run safe dir
        run: |
          git config --global --add safe.directory /github/workspace
      - name: Push Bookmark README
        run: |
          git config user.name bgzo
          git config user.email lfh010618@gmail.com
          git add .
          git commit -m "Update Porgress"
          git push