# This is a basic workflow to help you get started with Actions

name: progress

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: output README
        run: |
          python3 progress.py > README.md
        
      - name: Push Git
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.G_T }}
          commit-message: "Update Porgress"
          files: .
          rebase: 'true'
          name: bGZoCg
          email: bgzocg@outlook.com
